### ISSUE TITLE
memory increase over time

### ISSUE THREAD

**Issue by Dunkem** [sikang/mpl_ros#10]
hi sikang:
I am running your simple code poly_map_planner_node, but the memory increase and the rviz doesn't show any thing.After a while my computer crash.My memory is 64G.
do you know why about this?

**Comment by sikang** [comment]
The memory is increasing due to the searching process, and the RVIZ only shows stuff once the planning is done. So I think this is normal except the searching takes too much space and time. Here are two things worth checking: 1. did you build the binary in Release mode? and 2. what is the configuration (discretization on time and control) you have? Try make coarser resolution and it should largely reduce the computation time...

**Comment by Dunkem** [comment]
Thank you for your reply.
First I build this project with command which you recommend "catkin_make_isolated -DCMAKE_BUILD_TYPE=Release".And I don't know how to change the configuration, but I find in 'poly_map_planner_node.cpp' the param use_config0 is true, use_config1 is false.
![screenshot from 2019-01-16 11-51-50](https://user-images.githubusercontent.com/30431146/51225627-627a3900-1986-11e9-8585-88f24e45b905.png).this picture shows my memory info before I launch your example.
![screenshot from 2019-01-16 12-03-49](https://user-images.githubusercontent.com/30431146/51225737-e3393500-1986-11e9-9f3b-2412f3f71fe7.png) After I launch your example, the memory increas until my computer crash

**Comment by sikang** [comment]
The default parameters in ``poly_map_planner_node'' is not set properly somehow, the goal is outside the map such that the planner cannot reach it and will keep searching for infinity time. The latest commit fixed this bug by extending the ``range_x'' default value from 15.0 to 20.0. Thanks for pointing this out!

**Comment by Dunkem** [comment]
It works，thanks for your help
