### ISSUE TITLE
Real time planning with slam

### ISSUE THREAD

**Issue by Changliu52** [sikang/mpl_ros#12]
Hi Sikang,
I'm currently running a visual slam and stereo depth together with voxblox mapping engine, which can publish surface point cloud from the incremental map. 

How would you recommend to implement the real-time replan using this package?

Thank you in advance.
Chang

**Comment by sikang** [comment]
The real-time performance largely depends on your system settings and environments. For moderate speed and map size, it should be fast enough to replan at ~10 Hz.

In order to use this lib, you may need to convert the point cloud you are using into the VoxelMap. Alternately, you can also re-write the collision checking function to directly use your point cloud.

You can try it, and let me know if there is any issue :)

Sikang

**Comment by Changliu52** [comment]
Yes. I adopted the map_planner_node and converted the pointcloud to VoxelMap. Working perfectly.
